spring:
  #redis配置
  redis:
    #数据库索引
    database: 0
    #ip
    host: 120.55.54.42
    #端口
    port: 6379
    #密码
    password: qwe12934ynbcskbih8Bxfty56nbr
    #超时时间（毫秒）
    timeout: 0
    jedis:
      pool:
        #最大连接数（负值表示没有限制）
        max-active: 8
        #最大阻塞等待时间（负值表示没有限制）
        max-wait: -1
        #最大空闲链接
        max-idle: 8
        min-idle: 0



  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #基本属性 url、username、password
    username: root
    password: 1qaz@WSX
    jdbc-url: jdbc:mysql://120.55.54.42:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    #配置初始化大小、最小、最大
    initial-size: 1
    max-active: 20
    min-idle: 1
    #配置获取连接等待超时的时间
    max-wait: 60000

    validation-query: select 'x'
    validationQueryTimeout: 5
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true

    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000

    filters: wall,stat
    filter:
      stat:
        enabled: true
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
        #db-type: sqlserver
      slf4j:
        enabled: true
        connection-log-enabled: true
        connection-close-after-log-enabled: true
        connection-commit-after-log-enabled: true
        connection-connect-after-log-enabled: true
        connection-connect-before-log-enabled: true
        connection-log-error-enabled: true
        data-source-log-enabled: true
        result-set-log-enabled: true
        statement-log-enabled: true
      wall:
        enabled: true
        config:
          alter-table-allow: false
          truncate-allow: false
          drop-table-allow: false
          #是否允许非以上基本语句的其他语句，缺省关闭，通过这个选项就能够屏蔽DDL
          none-base-statement-allow: false
          #检查UPDATE语句是否无where条件，这是有风险的，但不是SQL注入类型的风险
          update-where-none-check: true
          #SELECT ... INTO OUTFILE 是否允许，这个是mysql注入攻击的常见手段，缺省是禁止的
          select-into-outfile-allow: false
          #是否允许调用Connection.getMetadata方法，这个方法调用会暴露数据库的表信息
          metadata-allow: true
          #允许多条sql一起执行
          multiStatementAllow: true
        #对被认为是攻击的SQL进行LOG.error输出
        log-violation: true
        #对被认为是攻击的SQL抛出SQLExcepton
        throw-exception: true
        #db-type: mysql
    web-stat-filter:
      enabled: true
      url-pattern: /*
      exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      #你可以配置principalSessionName，使得druid能够知道当前的cookie的用户是谁
      #principal-cookie-name: admin
      #你可以配置principalSessionName，使得druid能够知道当前的session的用户是谁
      #principal-session-name: admin
      #设置profileEnable能够监控单个url调用的sql列表。
      profile-enable: true
      #session统计功能
      session-stat-enable: false
      #最大session数
      session-stat-max-count: 100000
    stat-view-servlet:
      #allow: ${GATEWAY_HOST:172.26.114.241}
      enabled: true
      login-username: ${DRUID_USER:admin}
      login-password: ${DRUID_PWD:admin}
      url-pattern: /druid/*
      #允许清除记录
      reset-enable: false
    aop-patterns: com.he.*


#mybatis-plus
mybatis-plus:
  #datasource: datasource
  mapper-locations: classpath*:/mapper/**Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.he.entity
  #该配置请和 typeAliasesPackage 一起使用，如果配置了该属性，则仅仅会扫描路径下以该类作为父类的域对象 。
  type-aliases-super-type: com.he.entity.BaseEntity
  #枚举类扫描路径，如果配置了该属性，会将路径下的枚举类进行注入，让实体类字段能够简单快捷的使用枚举属性。
  typeEnumsPackage: com.he.enums
  #typeHandlersPackage:
  #指定外部化 MyBatis Properties 配置，通过该配置可以抽离配置，实现不同环境的配置部署。
  #configuration-properties: classpath:mybatis/config.properties
  global-config:
    db-config:
      #主键类型
      id-type: id_worker
      #字段策略
      field-strategy: not_null
      #是否开启大写命名，默认不开启
      #capital-mode: true
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 0
      logic-not-delete-value: 1
  configuration:
    #默认枚举处理类,如果配置了该属性,枚举将统一使用指定处理器进行处理
    #org.apache.ibatis.type.EnumTypeHandler: 存储枚举的名称
    #org.apache.ibatis.type.EnumOrdinalTypeHandler: 存储枚举的索引
    #com.baomidou.mybatisplus.extension.handlers.EnumTypeHandler: 枚举类需要实现IEnum接口或字段标记@EnumValue注解.
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.EnumTypeHandler
    #是否开启自动驼峰命名规则映射，即从经典数据库列名A_COLUMN（下划线命名）到经典Java属性名aColumn（驼峰命名）的类似映射。
    #默认true
    map-underscore-to-camel-case: false
    #全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存，默认为 true。
    cache-enabled: false


# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"

logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG